spring:
  flyway.schemas: foo
  datasource:
    url: jdbc:postgresql://postgres/foo?currentSchema=foo
    driverClassName: org.postgresql.Driver
    username: foo
    password: foo
    hikari:
      maximum-pool-size: 5

    bar:
      url: jdbc:postgresql://postgres/bar?currentSchema=bar
      driverClassName: org.postgresql.Driver
      username: bar
      password: bar
      hikari:
        maximum-pool-size: 5

